### PR TITLE
Feat/1090 introduce gatsby

### PR DESCRIPTION
**Pull request by KaZiUpl**
### Status
- [x] Ready for review
(If not, write either WIP or blocked)

### Summary

Migrated whole modino.io to Gatsby
### Motivation - All related issues
- [x] I have linked all related issues
#### Issues: 

Closes Modino-io/modino#1090
Closes Modino-io/modino#938
Closes Modino-io/modino#1171
### Validation
- [x] I have made sure no other tests have to be added or updated before this pull request is merged / created a new issue aimed to update them (link the issue if needed)

### Checklist

- [x] I have self-reviewed my changes
- [x] I have made sure all BREAKING CHANGEs were marked accordingly (see [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and [semantic-release](https://github.com/semantic-release/semantic-release))
- [x] I have made sure documentation is up to date or created a new issue aimed to update it (link the issue if needed)
- [x] I have made sure that my changes do not require (or break) configuration of other services, e.g. Kubernetes/Docker-compose or created a new issue aimed at addressing this task
- [x] No other pull requests have to be merged / issues have to be solved before this one

### Other information (_optional_)

### CODE REVIEW

**Review by pawelsobkowski — DISMISSED** [review]
LGTM

**Review by pawelsobkowski — APPROVED** [review]

**Comment by KaZiUpl** [comment]
@Coldver Please take a look at the [README](https://github.com/Modino-io/modino-website/tree/feat/1090-introduce-gatsby) and check whether it's clear to you.

**Review by pawelsobkowski — APPROVED** [review]

**Comment by Coldver** [comment]
> @Coldver Please take a look at the [README](https://github.com/Modino-io/modino-website/tree/feat/1090-introduce-gatsby?tab=readme-ov-file#how-to-add-new-article) and check whether it's clear to you.

Two things to add/explain in the README file currently:
- Is there a way for formatting text like bold, italic or underline? 
- The text size increase/decrease also should be mentioned as we have different headings in the articles
That's it for know, but I am pretty sure that additional questions will arise during actual work.

**Comment by KaZiUpl** [comment]
> > @Coldver Please take a look at the [README](https://github.com/Modino-io/modino-website/tree/feat/1090-introduce-gatsby?tab=readme-ov-file#how-to-add-new-article) and check whether it's clear to you.
> 
> Two things to add/explain in the README file currently:
> 
> * Is there a way for formatting text like bold, italic or underline?
> * The text size increase/decrease also should be mentioned as we have different headings in the articles
>   That's it for know, but I am pretty sure that additional questions will arise during actual work.

The things you mentioned are just a part of Markdown syntax (which I explained in case of images), so using multiple `#` for headings, and using `*` for italic and bold text. Underline is not available in Markdown as far as I know, although I think you can enclose your text in `<u>` tag to achieve underlining, e.g. `<u>you underlined text</u>`.

When creating article you use Markdown syntax so everything that Markdown can do, should albo be possible in the article's text.

**Pull request merged**
